version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:${MYSQLV}
    restart: on-failure
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORTS}

  nginx:
    container_name: nginx
    image: ${NGINXV}
    restart: on-failure
    volumes:
      - ${NGINX_VOLUME_CONF}
    ports:
      - ${NGINX_PORTS}
    depends_on:
      - php

  php:
    container_name: ${PHP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ${PHP_PATH_DOCKERFILE}
    restart: on-failure
    volumes:
      - ${PHP_VOLUME_WORKING_DIR}
    user: ${PHP_USER}
    working_dir: ${PHP_WORKING_DIR}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sf4_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${PMA_PORT}
    ports:
      - ${PHPMYADMIN_PORTS}
    links:
      - mysql

  maildev:
    image: djfarrelly/maildev
    container_name: maildev
    ports:
      - 8001:80